### ISSUE TITLE
Website: Establish Development and Design Contents

### ISSUE THREAD

**Issue by TyzerDevera** [outsoar-ph/outsoar#75]

**Comment by Macangel23** [comment]
Project Manager:

- [ ] Tyzer checklist

Developers:
- [ ] Code Review of NUXTJS implementation
- [ ] Change content text of "Develop and Design"
- [ ] Add/Change content inside "Develop and Design page"

**Comment by TyzerDevera** [comment]
- [ ] Create ideal content for Development and design
- [ ] Proposal to be approved by Sir Ash
- [ ] Relay contents to be apply in website by developer
